--프로그래머스 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기 https://school.programmers.co.kr/learn/courses/30/lessons/151139

SELECT 
  CASE 
    WHEN MONTH = '08' THEN '8'
    WHEN MONTH = '09' THEN '9'
    ELSE '10'
    END AS MONTH,
    CAR_ID, RECORDS
FROM (
  SELECT TO_CHAR(H.START_DATE, 'MM') AS MONTH, 
    H.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H,
    (SELECT CAR_ID, COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYYMM') >= '202208'
      AND TO_CHAR(START_DATE, 'YYYYMM') <= '202210'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5) A
  WHERE A.CAR_ID = H.CAR_ID
    AND TO_CHAR(START_DATE, 'YYYYMM') >= '202208'
    AND TO_CHAR(START_DATE, 'YYYYMM') <= '202210'
  GROUP BY H.CAR_ID, TO_CHAR(H.START_DATE, 'MM')
  ORDER BY MONTH ASC, H.CAR_ID DESC
)
;