--프로그래머스 조건에 맞는 사용자와 총 거래금액 조회하기 https://school.programmers.co.kr/learn/courses/30/lessons/164668

SELECT WRITER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID
	AND STATUS = 'DONE'
GROUP BY WRITER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES
;

