--프로그래머스 즐겨찾기가 가장 많은 식당 정보 출력하기 https://school.programmers.co.kr/learn/courses/30/lessons/131123

SELECT A.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A,
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) B
WHERE FAVORITES = MAX_FAVORITES 
	AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY FOOD_TYPE DESC
;