--프로그래머스 5월 식품들의 총매출 조회하기 https://school.programmers.co.kr/learn/courses/30/lessons/131117

SELECT P.PRODUCT_ID, PRODUCT_NAME, PRICE*SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
	AND P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID, PRODUCT_NAME, PRICE
ORDER BY PRICE*SUM(AMOUNT) DESC, P.PRODUCT_ID
;