--프로그래머스 년, 월, 성별 별 상품 구매 회원 수 구하기 https://school.programmers.co.kr/learn/courses/30/lessons/131532

SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR, 
	TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH, 
    GENDER, COUNT(distinct U.USER_ID) AS USERS
FROM USER_INFO U, ONLINE_SALE S
WHERE U.USER_ID = S.USER_ID
	AND GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), 
	TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')), GENDER 
ORDER BY YEAR, MONTH, GENDER
;