--프로그래머스 서울에 위치한 식당 목록 출력하기 https://school.programmers.co.kr/learn/courses/30/lessons/131118

SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
	ROUND(SUM(REVIEW_SCORE)/COUNT(*), 2) AS SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.REST_ID = R.REST_ID
	AND ADDRESS LIKE '서울%'
GROUP BY I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY ROUND(SUM(REVIEW_SCORE)/COUNT(*), 2) DESC, FAVORITES DESC
;