--프로그래머스 가격이 제일 비싼 식품의 정보 출력하기 https://school.programmers.co.kr/learn/courses/30/lessons/131115

SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_CD,CATEGORY,PRICE
FROM FOOD_PRODUCT
WHERE PRICE = 
(SELECT * FROM (SELECT A.PRICE FROM FOOD_PRODUCT A
 ORDER BY A.PRICE DESC) WHERE ROWNUM <= 1)
;